import java.io.*;

/**
 * CoreIPC.java
 *
 * Handles the Core Process side of communication
 * using a named pipe / FIFO represented by a file.
 *
 * The Core receives commands and sends responses.
 */
public class CoreIPC {

    private final CoreProcess core;
    private final CoreCommandHandler commandHandler;

    /**
     * Creates the Core IPC handler.
     */
    public CoreIPC(CoreProcess core) {
        this.core = core;
        this.commandHandler = new CoreCommandHandler(core);
    }

    /**
     * Processes one command received through IPC.
     *
     * @param command command received from another process
     * @return response generated by Core
     */
    public String processCommand(String command) {

        CoreResponse response =
                commandHandler.handleCommand(command);

        return response.toString();
    }

    /**
     * Returns the Core Process.
     */
    public CoreProcess getCore() {
        return core;
    }
}