/**
 * CoreIPC.java
 *
 * Core-side IPC interface.
 *
 * This class prepares the Core Process to communicate
 * using the team's selected Named Pipe / FIFO mechanism.
 *
 * Pipe name:
 * tata_core_pipe
 */
public class CoreIPC {

    // Agreed IPC pipe name
    private static final String PIPE_NAME = "tata_core_pipe";

    // Core Process
    private final CoreProcess core;

    // Command handler
    private final CoreCommandHandler commandHandler;

    /**
     * Creates the Core IPC interface.
     *
     * @param core Core Process instance
     */
    public CoreIPC(CoreProcess core) {
        this.core = core;
        this.commandHandler = new CoreCommandHandler(core);
    }

    /**
     * Returns the name of the IPC pipe.
     *
     * @return pipe name
     */
    public String getPipeName() {
        return PIPE_NAME;
    }

    /**
     * Processes a command received through IPC.
     *
     * The existing CoreCommandHandler returns a String,
     * so the IPC layer also returns that String.
     *
     * @param command command received from another process
     * @return response generated by the Core
     */
    public String processCommand(String command) {
        return commandHandler.handleCommand(command);
    }

    /**
     * Returns the Core Process.
     *
     * @return Core Process
     */
    public CoreProcess getCore() {
        return core;
    }

    /**
     * Starts the Core IPC interface.
     *
     * The actual operating-system pipe connection will be
     * connected after the team finalizes the common IPC
     * communication format.
     */
    public void start() {
        System.out.println("=================================");
        System.out.println("        CORE IPC STARTED");
        System.out.println("=================================");
        System.out.println("Pipe Name: " + PIPE_NAME);
        System.out.println("Waiting for IPC commands...");
    }

    /**
     * Stops the Core IPC interface.
     */
    public void stop() {
        System.out.println("Core IPC stopped.");
    }
}